languageCode = "es"
languageName = "Spanish"
weight = 1
title = "El PoshoX"

[params]
  displayName = "ES"
  isoCode = "es"
  rtl = false
  dateFormat = "2 Enero 2006"
  logo = "img/elposhox_logo_transparent.png"
  description = "Tech Blog of my day to day"

[params.author]
  name = "Az García Zúñiga"
  image = "img/elposhox_logo.png"
  headline = "Robot pretendiendo escribir artículos como humano"
  bio = "Soy un <i>Nerdy</i> al que le encanta escribir sobre su vida diaria sobre temas como DevOps, SRE, Cloud, y más."
  links = [
    { link = "https://elposhox.dev/" },
    { facebook = "https://facebook.com/ElPoshox.dev" },
    { github = "https://github.com/username" },
    { instagram = "https://instagram.com/elposhox.dev" },
    { linkedin = "https://www.linkedin.com/in/azgad-adrian-merced-iii-garc%C3%ADa-z%C3%BA%C3%B1iga-809890a0/" },
    { medium = "https://medium.com/@elposhox.dev" },
    # { tiktok = "https://tiktok.com/@username" },
    { youtube = "https://www.youtube.com/@elposhoxdev" },
    { ko-fi = "https://ko-fi.com/elposhox" },
  ]
