name: Update Latest Posts
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write # To write the generated contents to the readme
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gautamkrishnar/blog-post-workflow@1.8.8
        with:
          max_post_count: "6"
          feed_list: "https://elposhox.github.io/blog/posts/index.xml"
